new Vue({
    el: '#app',
    data: {
        fullName: 'Radhwan Rouihm',
        jobTitle: 'Full Stack Developer 👨‍💻',
        aboutMe: "I am a highly motivated Full Stack Developer with 6 years of experience in Web Development, specializing in PHP. I have a proven track record of delivering high-quality projects to clients and am skilled in all aspects of the development process, including front-end design, back-end development, and database management.I am dedicated to staying up-to-date with the latest technologies and trends in the industry, and am constantly learning and exploring new technologies. My strong discipline, attention to detail, and fast learning abilities have enabled me to quickly adapt to new challenges and deliver outstanding results.I am passionate about web development and thrive in collaborative team environments. I have excellent communication skills and am able to effectively work with clients and team members to deliver projects on time and within budget.",
        email: 'radhwanrouihm@gmail.com',
        phone: '(+216) 28522280',
        github: 'https://github.com/radhwanben',
        skills: [
            { name: 'PHP', icon: '🐘' },
            { name: 'Python', icon: '🐍' },
            { name: 'AWS', icon: '☁️' },
            { name: 'Google Cloud', icon: '🌐' },
            { name: 'Heroku', icon: '🚀' },
            { name: 'Bootstrap', icon: '🅱️' },
            { name: 'Django', icon: '🎸' },
            { name: 'jQuery', icon: '🔍' },
            { name: 'Laravel', icon: '🌐' },
            { name: 'Symfony', icon: '⚙️' },
            { name: 'Vue.js', icon: '🖌️' },
            { name: 'Apache', icon: '🚦' },
            { name: 'Nginx', icon: '🌐' },
            { name: 'MySQL', icon: '📦' },
            { name: 'Postgres', icon: '🐘' },
            { name: 'SQLite', icon: '📱' },
            { name: 'MongoDB', icon: '🍃' },
            { name: 'MariaDB', icon: '🐬' },
            { name: 'LINUX', icon: '🐧' },
            // Add more skills as needed
        ],
        experiences: [
            {
                title: 'PART-TIME Project Manager',
                company: 'MKS Consulting',
                date: '11/2023 - Present',
                tasks: [
                    'Lead and manage projects with a focus on delivering high-quality results',
                    'Coordinate project teams, define project scope, and ensure timely delivery',
                    'Conceptualize and implement a platform similar to Upwork for MKS Consulting',
                    'Collaborate with clients to understand project requirements and expectations',
                    'Ensure effective communication and collaboration among team members',
                    'Track project progress, manage resources, and address challenges proactively',
                    'Stay updated with industry trends and implement best practices in project management',
                ],
                technologies: ['Project Management', 'Team Collaboration', 'Client Communication', 'Upwork-like Platform Concept'],
            },
            {
                title: 'Full Stack Developer',
                company: 'Clinfile – MultiHealth Group',
                date: '12/2022 - Present',
                tasks: [
                    ' Optimize existing PHP code for improved performance and scalability',
                    ' Analyze and debug existing PHP code to identify and fix bugs',
                    ' Develop new features based on client requirements',
                    ' Conduct code reviews and ensure code quality',
                    ' develop bundles for Symfony projects that can be reusable in any other  project like reporting dynamics based on user selection and generate charts with charts',
                    ' database design of patient file medical  for treatment using EAV model'
                ],
                technologies: ['PHP', 'MySQL', 'API PLATFORM', 'Symfony'],
            },
            {
                title: 'Team Lead Web Developer',
                company: 'Credit Healing LLC',
                date: '09/2022 - Present',
                tasks: [
                    ' Lead a team in developing web applications with Laravel and Vue.js',
                    " develop Python scrapy to get data from one provider who didn't have API using python ",
                    ' create a payment system using stripe and authorize.net with lot type single payment subscription ...',
                    ' create system allow the super user of the platform to create an automated emails templates with injection of the right data  ',
                ],
                technologies: ['Laravel', 'Vue.js', 'AWS', 'HTML', 'CSS', 'JavaScript', 'PHPUnit', 'AUTHORIZE.NET'],
            },
            {
                title: 'Full Stack Developer',
                company: 'handsonsystems',
                date: '08/2022 - 11/2022',
                tasks: [
                    'Develop and maintain APIs using PHP OOP to communicate with GPS tracking devices and retrieve location data',
                    'Design and develop dashboard interfaces using Laravel and Livewire for the fleet management system to visualize the GPS tracking data and monitor the status of vehicles',
                    'Implement features such as real-time tracking, route optimization, geofencing, and driver behavior monitoring',
                    'Work with cross-functional teams including product management, UI/UX design, and quality assurance to define project requirements and deliver high-quality software products',
                    'Conduct code reviews, ensure adherence to coding standards, and improve code quality',
                    'Troubleshoot and debug issues related to GPS tracking and fleet management systems',
                    'Stay up-to-date with the latest web development technologies and best practices, and implement them in the project as needed',
                ],
                technologies: ['PHP', 'MySQL', 'API', 'OOP', 'HTML', 'Laravel', 'Livewire', 'JavaScript'],
            },
            {
                title: 'Instructor/Trainer for PHP/Web Development',
                company: 'Fiverr',
                date: '02/2018 - Today',
                tasks: [
                    'Plan, prepare, and deliver lessons that tutor PHP basics, the SOLID principles, MVC PHP application, and Object-Oriented Programming with SQL, MySQL, OOP, HTML, CSS, Cybersecurity',
                    'Teach the process of building projects fully based on PHP OOP',
                    'Instruct the creation of databases inserted with PHP (PDO, MySQL)',
                    'Guide students in building Laravel Projects from scratch with API Integration and creating custom API',
                    'Teach methods to secure PHP projects from cyber security threats',
                ],
                technologies: ['PHP', 'MySQL', 'API', 'OOP', 'HTML', 'Cyber Security'],
                url: 'https://www.fiverr.com/radhwanben',
            },
            {
                title: 'Full Stack Web Developer',
                company: 'Various PHP/Laravel/Symfony customer projects',
                date: '01/2017 - Today',
                tasks: [
                    'Implement PHP Packages in various web applications',
                    'Upgrade PHP procedure code to Object-Oriented Programming',
                    'Create databases',
                    'Create PHP API for hybrid applications',
                    'Update web system functions',
                    'Test PHP codes and applications',
                    'Co-build a digital solution',
                    'Build static websites and local web applications',
                    'Create a custom authentication system and integrate Facebook and Google API',
                    'Get Facebook events data from their API and display it in Laravel',
                    'Project to users according to their interests',
                    'Get localization data from Google Maps API then display the nearest places and store the search request',
                    'Create custom plugins for WordPress',
                    'Build Stock Management System with PHP OOP & MySQL',
                    'Write security audit for Websites and Server',
                ],
                technologies: ['PHP', 'Laravel', 'Symfony', 'MySQL', 'HTML', 'CSS', 'JavaScript', 'Git', 'SQL', 'Web Development', 'JSON', 'RESTful API', 'Object-Oriented Programming', 'API Integration', 'Postman', 'Bootstrap', 'XML', 'WordPress (Theme Development)', 'Prestashop'],
            },
        ],
        projects: [
            {
                name: 'Local Organization Event Matching',
                description: 'Developed a platform for a local organization allowing users to log in with Facebook, retrieve their events, and share matched events per category in their dashboard.',
                link: 'https://github.com/radhwanben/Facelaraevent',
            },
            {
                name: 'ERP for Master Control',
                description: 'Developed an ERP system for Master Control, serving as the technical hub of a broadcast operation. Included features for creating dashboards, reports, and managing issues.',
                link: 'https://gitlab.com/radhwanben/tmc',
            },
            {
                name: 'Zakat Calculator',
                description: 'Built an application for calculating Zakat in Islamic finance. Implemented features to input financial data, calculate Zakat, and provide information on Islamic financial principles.',
                link: 'https://github.com/radhwanben/zakat',
            },
            {
                name: 'Real State website',
                description: 'Developed a platform for a selling and buying houses',
                link: 'https://github.com/radhwanben/lupangos-new',
            },
        ],
        
            // Add more projects as needed
    }
});
